// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221217035703_update3")]
    partial class update3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_StatusPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_StatusReviceOrder")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Total")
                        .HasColumnType("int");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_checkout")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.Property<string>("introduce_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Zalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("introduce_Id");

                    b.HasIndex("introduce_UserCreate");

                    b.ToTable("IntroducePage", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Property<string>("pc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_Id");

                    b.ToTable("PetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            pc_Id = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pc_Description = "Guard dog",
                            pc_IsDelete = false,
                            pc_Name = "Guard dog"
                        },
                        new
                        {
                            pc_Id = "61786aa4-4c21-4ef1-9df4-4c5c914497a3",
                            pc_Description = "Sheepdogs",
                            pc_IsDelete = false,
                            pc_Name = "Sheepdogs"
                        },
                        new
                        {
                            pc_Id = "f4fd09b3-ed4e-4acd-b2ee-3e56a22b877b",
                            pc_Description = " Sled dogs",
                            pc_IsDelete = false,
                            pc_Name = " Sled dogs"
                        },
                        new
                        {
                            pc_Id = "6c8bdcfa-efe6-415f-ad09-6649fc421aa9",
                            pc_Description = "Hound",
                            pc_IsDelete = false,
                            pc_Name = "Hound"
                        });
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Property<string>("pet_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pet_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pet_Lifespan")
                        .HasColumnType("float");

                    b.Property<string>("pet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_OrtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pet_Price")
                        .HasColumnType("float");

                    b.Property<double>("pet_Weight")
                        .HasColumnType("float");

                    b.HasKey("pet_Id");

                    b.HasIndex("pet_CategoryId");

                    b.ToTable("Pets", (string)null);

                    b.HasData(
                        new
                        {
                            pet_Id = "773de315-cf2b-4b46-b83d-f64dccb9f58d",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cooker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "Japan",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "6eb9e3e6-3137-4bc6-8a38-b4341092a683",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BECGIE Belgium (MALINOIS)",
                            pet_ImgUrl1 = "image/giongcho/becgie-bi.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-dobermann-2thang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Belgium (MALINOIS)",
                            pet_Origin = "BECGIE Belgium (MALINOIS)",
                            pet_OrtherName = "BECGIE Belgium (MALINOIS)",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "e15824c1-d7eb-4dad-af23-1b36e133a100",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BECGIE Germany",
                            pet_ImgUrl1 = "image/giongcho/becgie-duc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodle-rautrang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Germany",
                            pet_Origin = "BECGIE Germany",
                            pet_OrtherName = "BECGIE Germany",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "5bbd5984-dab4-4c96-90f6-5c69e37e17c5",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BORDER COLLIE",
                            pet_ImgUrl1 = "image/giongcho/BORDER-COLLIE.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuouden.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BORDER COLLIE",
                            pet_Origin = "BORDER COLLIE",
                            pet_OrtherName = "BORDER COLLIE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "9a2d9baa-f80f-468c-979a-ae08599d5096",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BULL France",
                            pet_ImgUrl1 = "image/giongcho/bull-phap.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-daingaohusky.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULL France",
                            pet_Origin = "BULL France",
                            pet_OrtherName = "BULL France",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "78c7fc25-57a1-4bd1-b0e7-edd4d2bddbd6",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BULLDOG",
                            pet_ImgUrl1 = "image/giongcho/bulldog.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hoangtutuyetsamoyed.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLDOG",
                            pet_Origin = "BULLDOG",
                            pet_OrtherName = "BULLDOG",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "935334e5-c249-4113-a545-a6fef432659e",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BULLY AMERICAN",
                            pet_ImgUrl1 = "image/giongcho/bully-american.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliecongchua.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLY AMERICAN",
                            pet_Origin = "BULLY AMERICAN",
                            pet_OrtherName = "BULLY AMERICAN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "e8f1cd87-11c3-498d-88b2-3ed8ac4d77a1",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "CHIHUAHUA",
                            pet_ImgUrl1 = "image/giongcho/chihuahua.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phosocnhonhan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHIHUAHUA",
                            pet_Origin = "CHIHUAHUA",
                            pet_OrtherName = "CHIHUAHUA",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "72c103d3-b5c2-49b1-b428-58379a16ec64",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cogaipitbull.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "77430a36-abe0-4f63-bcce-2f6c331321a1",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "CHOW CHOW",
                            pet_ImgUrl1 = "image/giongcho/chow-chow.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliemui2.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHOW CHOW",
                            pet_Origin = "CHOW CHOW",
                            pet_OrtherName = "CHOW CHOW",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "c842993b-9e2d-4696-b635-20df9b5389d7",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "CORGI",
                            pet_ImgUrl1 = "image/giongcho/corgy.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goodboyrottweiler.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CORGI",
                            pet_Origin = "CORGI",
                            pet_OrtherName = "CORGI",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "5288b349-32a3-4296-ae2f-de041c6df988",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "DOBERMANN",
                            pet_ImgUrl1 = "image/giongcho/dobermann.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hotboylabrador.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "DOBERMANN",
                            pet_Origin = "DOBERMANN",
                            pet_OrtherName = "DOBERMANN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "0a74ed3e-33a3-4543-b9ba-f2fe0ae165cc",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "GOLDEN RETRIEVER",
                            pet_ImgUrl1 = "image/giongcho/golden-retriever.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgieduc.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GOLDEN RETRIEVER",
                            pet_Origin = "GOLDEN RETRIEVER",
                            pet_OrtherName = "GOLDEN RETRIEVER",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "86647be1-2518-4d35-bc72-969399ec5fdb",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "GREAT DANE",
                            pet_ImgUrl1 = "image/giongcho/great-dane.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-lapxuongsocola.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GREAT DANE",
                            pet_Origin = "GREAT DANE",
                            pet_OrtherName = "GREAT DANE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "026c242c-3628-41d3-86e0-4252d5630da3",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "H'Mong Coc",
                            pet_ImgUrl1 = "image/giongcho/mong-coc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuoutimsen.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "H'Mong Coc",
                            pet_Origin = "H'Mong Coc",
                            pet_OrtherName = "H'Mong Coc",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "e9cce766-518d-4ad6-9417-715898527868",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goldenretriever.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "AKITA INU",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "9a50403b-6f5a-4a7d-a553-ef36a85c4e8f",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "ALASKA",
                            pet_ImgUrl1 = "image/giongcho/alaska.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-alaskamummim.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "ALASKA",
                            pet_Origin = "ALASKA",
                            pet_OrtherName = "ALASKA",
                            pet_Price = 100.0,
                            pet_Weight = 23.0
                        },
                        new
                        {
                            pet_Id = "f5c054ad-6eed-4bba-acd1-5c6d67bd4d7d",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "BĂC HÀ",
                            pet_ImgUrl1 = "image/giongcho/chobacha.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bulldogmapmapa.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BĂC HÀ",
                            pet_Origin = "BĂC HÀ",
                            pet_OrtherName = "BĂC HÀ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "b74e9bc3-ed32-4ecf-b717-be8400b0bd49",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "Pekingese",
                            pet_ImgUrl1 = "image/giongcho/chobackinh.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chowchow.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Pekingese",
                            pet_Origin = "Pekingese",
                            pet_OrtherName = "Pekingese",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "088436d8-d987-4522-a30e-bd0fda7a9264",
                            pet_CategoryId = "61786aa4-4c21-4ef1-9df4-4c5c914497a3",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cocker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "2dcc6b00-0c20-4e32-aa10-7c53fcd40342",
                            pet_CategoryId = "61786aa4-4c21-4ef1-9df4-4c5c914497a3",
                            pet_Description = "Japan Dog",
                            pet_ImgUrl1 = "image/giongcho/chonhatban.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-pugdangyeu.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Japan Dog",
                            pet_Origin = "Japan Dog",
                            pet_OrtherName = "Japan Dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "290dd269-daf0-483f-9683-5f05c7eeebff",
                            pet_CategoryId = "f4fd09b3-ed4e-4acd-b2ee-3e56a22b877b",
                            pet_Description = "Tibetan Clams",
                            pet_ImgUrl1 = "image/giongcho/ngaottang.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-golden1.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Tibetan Clams",
                            pet_Origin = "Tibetan Clams",
                            pet_OrtherName = "Tibetan Clams",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "35b16072-ebdb-4864-8dee-1b4b74e45254",
                            pet_CategoryId = "61786aa4-4c21-4ef1-9df4-4c5c914497a3",
                            pet_Description = "Deer Pug dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-huou.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodlecuoituoi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Deer Pug dog",
                            pet_Origin = "Deer Pug dog",
                            pet_OrtherName = "Deer Pug dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "b47dff11-4901-4716-b516-4a8bac0dfac7",
                            pet_CategoryId = "f4fd09b3-ed4e-4acd-b2ee-3e56a22b877b",
                            pet_Description = "Phoc squirrel dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-soc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chuboss.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phoc squirrel dog",
                            pet_Origin = "Phoc squirrel dog",
                            pet_OrtherName = "Phoc squirrel dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "261aea03-01ce-44f2-b0aa-9f27483af16a",
                            pet_CategoryId = "f4fd09b3-ed4e-4acd-b2ee-3e56a22b877b",
                            pet_Description = "Phu Quoc dogs",
                            pet_ImgUrl1 = "image/giongcho/phu-quoc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgiehalan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phu Quoc dogs",
                            pet_Origin = "Phu Quoc dogs",
                            pet_OrtherName = "Phu Quoc dogs",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "801410f8-1f1f-4bce-b45d-6dcb4b5ca99b",
                            pet_CategoryId = "f4fd09b3-ed4e-4acd-b2ee-3e56a22b877b",
                            pet_Description = "PITBULL",
                            pet_ImgUrl1 = "image/giongcho/pitbull.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-corgi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "PITBULL",
                            pet_Origin = "PITBULL",
                            pet_OrtherName = "PITBULL",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "52b61299-3973-44c9-9945-3195a1c86c50",
                            pet_CategoryId = "eea1916a-5d5e-4b86-a1dd-0e8ba64b79de",
                            pet_Description = "SHIBA INU ",
                            pet_ImgUrl1 = "image/giongcho/shiba.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuou.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "SHIBA INU ",
                            pet_Origin = "SHIBA INU ",
                            pet_OrtherName = "SHIBA INU ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        });
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.Property<string>("pib_PetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pib_Quantity")
                        .HasColumnType("int");

                    b.HasKey("pib_PetId", "pib_BillId");

                    b.HasIndex("pib_BillId");

                    b.ToTable("PettInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Property<string>("proc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("proc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("proc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proc_Id");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            proc_Id = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            proc_Description = "newCategories_Id1",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id1"
                        },
                        new
                        {
                            proc_Id = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            proc_Description = "newCategories_Id2",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id2"
                        },
                        new
                        {
                            proc_Id = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            proc_Description = "newCategories_Id3",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id3"
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.Property<string>("proib_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("proib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("proib_ProductId", "proib_BillId");

                    b.HasIndex("proib_BillId");

                    b.ToTable("ProductInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("product_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<double>("product_Rate")
                        .HasColumnType("float");

                    b.Property<double>("product_ReProducePrice")
                        .HasColumnType("float");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "6d4d2a99-dcc1-4b45-8842-8279e5f4b437",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Transparent Backpack For Dogs and Cats",
                            product_Img = "image/phukien/phukien-balotrongsuot.png",
                            product_IsDelete = false,
                            product_Name = "Transparent Backpack For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "4068a814-04ef-42eb-9dca-4bacef217ffe",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Training Whistle",
                            product_Img = "image/phukien/phukien-coihuanluyen.png",
                            product_IsDelete = false,
                            product_Name = "Training Whistle",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "7ba0f5fb-17a2-45d9-b266-8925bd710169",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Lamb Sticks",
                            product_Img = "image/phukien/phukien-thitcuuque.png",
                            product_IsDelete = false,
                            product_Name = "Lamb Sticks",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "72c89dc3-bdc4-4e68-ab0b-e5a6f54a4abf",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "SmartHeart For Small Dogs",
                            product_Img = "image/phukien/phukien-SmartHeart.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Small Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "89843ed5-844e-410f-a243-9deaa1a17dbc",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Bonus Cake Tablets",
                            product_Img = "image/phukien/phukien-banhthuong.png",
                            product_IsDelete = false,
                            product_Name = "Bonus Cake Tablets",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "55a36ede-242b-4392-8547-65401b0b7434",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Royal Canin For Adult Dogs",
                            product_Img = "image/phukien/phukien-royal_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Adult Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "88fb930d-c120-4175-a2e3-205079014302",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Pair of Bows",
                            product_Img = "image/phukien/phukien-capno.png",
                            product_IsDelete = false,
                            product_Name = "Pair of Bows",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "dc3b7dc9-dd60-4b6b-bf55-facd342865e1",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Princess Lace Scarf",
                            product_Img = "image/phukien/phukien-khanren.png",
                            product_IsDelete = false,
                            product_Name = "Princess Lace Scarf",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "e794e6fd-26cd-4d99-bc60-d3f7220e7815",
                            product_CategoryId = "8dda779d-1cca-4e58-9a8d-5b7b22e3b881",
                            product_Description = "Drugs of Calcium",
                            product_Img = "image/phukien/phukien-thuoccanxi.png",
                            product_IsDelete = false,
                            product_Name = "Drugs of Calcium",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "db995cc0-cefc-4cc4-b28f-764f81b3266e",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "Bow Bow Bra",
                            product_Img = "image/phukien/phukien-aongucnochuong.png",
                            product_IsDelete = false,
                            product_Name = "Bow Bow Bra",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "8cb96a1a-6352-4a86-ba70-c02963d82c43",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "Balloon Toys",
                            product_Img = "image/phukien/phukien-bongbongdochoi.png",
                            product_IsDelete = false,
                            product_Name = "Balloon Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "ce9f6a32-1eb4-46eb-9b49-7a2c040cbc5d",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "Dog Fence",
                            product_Img = "image/phukien/phukien-raoquaycho.png",
                            product_IsDelete = false,
                            product_Name = "Dog Fence",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "9eeaa337-0e8b-4aff-9378-81a7a98a9df5",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "950e1b97-fcc9-41a7-859a-e4708646984f",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "Toys",
                            product_Img = "image/phukien/phukien-dochoi.png",
                            product_IsDelete = false,
                            product_Name = "Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "554ee466-0025-4871-a5f3-6d6ba5a6fc9f",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamFay.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "d2d81cec-ed1b-49db-9c12-07e668c5e0f2",
                            product_CategoryId = "bbc7b432-18f9-4cf6-9cc5-5f96fcc413af",
                            product_Description = "Anti-Tear Syrup",
                            product_Img = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_IsDelete = false,
                            product_Name = "Anti-Tear Syrup",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "5c32ddd1-07ff-4ebf-b9e8-73edc0b276de",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = "Lice Treatment Ring",
                            product_Img = "image/phukien/phukien-vongtriveran.png",
                            product_IsDelete = false,
                            product_Name = "Lice Treatment Ring",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "846d56ea-2608-464f-a85b-2f0fc2b9297d",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = "HANTOC Lice Spray",
                            product_Img = "image/phukien/phukien-xitveranHANTOC.png",
                            product_IsDelete = false,
                            product_Name = "HANTOC Lice Spray",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "111d6413-69c3-403f-a84b-72a5403d09be",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = ">Nutri-Nutrition Gel",
                            product_Img = "image/phukien/phukien-gelddNutri.png",
                            product_IsDelete = false,
                            product_Name = ">Nutri-Nutrition Gel",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "35d5bd1d-2d5e-4ec6-8740-0e2225b030f1",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = "Bio Milk Powder For Dogs and Cats",
                            product_Img = "image/phukien/phukien-suabotchomeo.png",
                            product_IsDelete = false,
                            product_Name = "Bio Milk Powder For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "3ddc1626-a6cf-4642-8a4b-a879d2145791",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = "Sleeky Multivitamin",
                            product_Img = "image/phukien/phukien-vitamintonghop.png",
                            product_IsDelete = false,
                            product_Name = "Sleeky Multivitamin",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "2c9c9745-c737-465a-884e-7afa8403f014",
                            product_CategoryId = "09fca3e8-ecd0-4354-9616-4bcd962e89a9",
                            product_Description = "Canxi Nano",
                            product_Img = "image/phukien/phukien-canxinano.png",
                            product_IsDelete = false,
                            product_Name = "Canxi Nano",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.Property<string>("uc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("uc_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uc_Id");

                    b.HasIndex("uc_UserCreate");

                    b.ToTable("UserContact", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2dae488e-7806-4791-8811-42c5a8fe8bf2",
                            RoleId = "1e93e3ad-1d4a-4ed7-b465-366855c53140"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1e93e3ad-1d4a-4ed7-b465-366855c53140",
                            ConcurrencyStamp = "87624484-7774-4dad-b8c5-42750a376d0e",
                            Name = "ADMIN",
                            NormalizedName = "admin",
                            Description = "admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");

                    b.HasData(
                        new
                        {
                            Id = "2dae488e-7806-4791-8811-42c5a8fe8bf2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67a3e9ab-8357-4801-a041-a7b2028d30cd",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEElCOfpKJBDsXylpViSyDnLB7U3ZKvIIxmradHacRE3zChhRRPMK4zQ17fbbLIe9vg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55a38683-96a6-4d6d-83c3-0339ecad9666",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            DoB = new DateTime(2022, 12, 17, 10, 57, 3, 529, DateTimeKind.Local).AddTicks(635),
                            FirstName = "FirstName",
                            LastName = "LastName",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.HasOne("Database.Entities.Users", "Users")
                        .WithMany("bill")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("introducePage")
                        .HasForeignKey("introduce_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.HasOne("Database.Entities.PetCategories", "petCategories")
                        .WithMany("pets")
                        .HasForeignKey("pet_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("petCategories");
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Pets", "pets")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Products", "products")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.HasOne("Database.Entities.ProductCategories", "productCategories")
                        .WithMany("products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("userContact")
                        .HasForeignKey("uc_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Navigation("pettInBill");

                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Navigation("pettInBill");
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.Navigation("bill");

                    b.Navigation("introducePage");

                    b.Navigation("userContact");
                });
#pragma warning restore 612, 618
        }
    }
}
