// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221217021832_updatebill")]
    partial class updatebill
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("bill_Cancel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StartDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StatusPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StatusReviceOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("bill_checkout")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.Property<string>("introduce_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Zalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("introduce_Id");

                    b.HasIndex("introduce_UserCreate");

                    b.ToTable("IntroducePage", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Property<string>("pc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_Id");

                    b.ToTable("PetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            pc_Id = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pc_Description = "Guard dog",
                            pc_IsDelete = false,
                            pc_Name = "Guard dog"
                        },
                        new
                        {
                            pc_Id = "a9a31160-91b1-4948-9e37-d7bdc8262531",
                            pc_Description = "Sheepdogs",
                            pc_IsDelete = false,
                            pc_Name = "Sheepdogs"
                        },
                        new
                        {
                            pc_Id = "5835d336-c69b-4069-baa2-94b8a6708845",
                            pc_Description = " Sled dogs",
                            pc_IsDelete = false,
                            pc_Name = " Sled dogs"
                        },
                        new
                        {
                            pc_Id = "3031b440-9bb5-4266-bce6-f7dc25b48b8c",
                            pc_Description = "Hound",
                            pc_IsDelete = false,
                            pc_Name = "Hound"
                        });
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Property<string>("pet_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pet_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pet_Lifespan")
                        .HasColumnType("float");

                    b.Property<string>("pet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_OrtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pet_Price")
                        .HasColumnType("float");

                    b.Property<double>("pet_Weight")
                        .HasColumnType("float");

                    b.HasKey("pet_Id");

                    b.HasIndex("pet_CategoryId");

                    b.ToTable("Pets", (string)null);

                    b.HasData(
                        new
                        {
                            pet_Id = "f48aa748-f197-4054-a3f7-417740a18bd0",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cooker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "Japan",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "e517650f-144c-42fe-9afc-349dc20833bc",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BECGIE Belgium (MALINOIS)",
                            pet_ImgUrl1 = "image/giongcho/becgie-bi.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-dobermann-2thang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Belgium (MALINOIS)",
                            pet_Origin = "BECGIE Belgium (MALINOIS)",
                            pet_OrtherName = "BECGIE Belgium (MALINOIS)",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "890939ba-88c7-44d3-9cfe-c46c51cd8ab3",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BECGIE Germany",
                            pet_ImgUrl1 = "image/giongcho/becgie-duc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodle-rautrang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Germany",
                            pet_Origin = "BECGIE Germany",
                            pet_OrtherName = "BECGIE Germany",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "2c6abf9f-a430-4589-a572-526374025c0f",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BORDER COLLIE",
                            pet_ImgUrl1 = "image/giongcho/BORDER-COLLIE.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuouden.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BORDER COLLIE",
                            pet_Origin = "BORDER COLLIE",
                            pet_OrtherName = "BORDER COLLIE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "f8917e26-5e47-4124-a276-5f57f0231963",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BULL France",
                            pet_ImgUrl1 = "image/giongcho/bull-phap.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-daingaohusky.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULL France",
                            pet_Origin = "BULL France",
                            pet_OrtherName = "BULL France",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "8ac566ad-f63f-45ad-a42d-05887db56476",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BULLDOG",
                            pet_ImgUrl1 = "image/giongcho/bulldog.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hoangtutuyetsamoyed.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLDOG",
                            pet_Origin = "BULLDOG",
                            pet_OrtherName = "BULLDOG",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "c383d9df-2f20-4440-a17a-bbd2d234e58f",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BULLY AMERICAN",
                            pet_ImgUrl1 = "image/giongcho/bully-american.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliecongchua.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLY AMERICAN",
                            pet_Origin = "BULLY AMERICAN",
                            pet_OrtherName = "BULLY AMERICAN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "4078a216-ba4f-4012-94dd-2269eee1d119",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "CHIHUAHUA",
                            pet_ImgUrl1 = "image/giongcho/chihuahua.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phosocnhonhan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHIHUAHUA",
                            pet_Origin = "CHIHUAHUA",
                            pet_OrtherName = "CHIHUAHUA",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "71e062f8-af88-4b58-9199-30be4b2ed8fe",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cogaipitbull.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "4c190b3c-266c-496f-b036-a89fd20d0348",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "CHOW CHOW",
                            pet_ImgUrl1 = "image/giongcho/chow-chow.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliemui2.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHOW CHOW",
                            pet_Origin = "CHOW CHOW",
                            pet_OrtherName = "CHOW CHOW",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "be93b759-cee7-4692-965a-9a4d1f474b9c",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "CORGI",
                            pet_ImgUrl1 = "image/giongcho/corgy.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goodboyrottweiler.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CORGI",
                            pet_Origin = "CORGI",
                            pet_OrtherName = "CORGI",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "2bd10413-f2e7-404b-a229-f06b1525d7a7",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "DOBERMANN",
                            pet_ImgUrl1 = "image/giongcho/dobermann.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hotboylabrador.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "DOBERMANN",
                            pet_Origin = "DOBERMANN",
                            pet_OrtherName = "DOBERMANN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "df0bd5ad-061a-4aef-bacc-7070483235a8",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "GOLDEN RETRIEVER",
                            pet_ImgUrl1 = "image/giongcho/golden-retriever.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgieduc.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GOLDEN RETRIEVER",
                            pet_Origin = "GOLDEN RETRIEVER",
                            pet_OrtherName = "GOLDEN RETRIEVER",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "1879837b-12cd-4e00-985d-40c74dd64cf7",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "GREAT DANE",
                            pet_ImgUrl1 = "image/giongcho/great-dane.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-lapxuongsocola.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GREAT DANE",
                            pet_Origin = "GREAT DANE",
                            pet_OrtherName = "GREAT DANE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "a915db85-34f6-4a4e-a3fd-e9c57ede2160",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "H'Mong Coc",
                            pet_ImgUrl1 = "image/giongcho/mong-coc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuoutimsen.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "H'Mong Coc",
                            pet_Origin = "H'Mong Coc",
                            pet_OrtherName = "H'Mong Coc",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "7d866118-5505-4706-ace8-502296435b06",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goldenretriever.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "AKITA INU",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "8305b9ca-b4e9-4ec8-a89b-e4115c677360",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "ALASKA",
                            pet_ImgUrl1 = "image/giongcho/alaska.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-alaskamummim.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "ALASKA",
                            pet_Origin = "ALASKA",
                            pet_OrtherName = "ALASKA",
                            pet_Price = 100.0,
                            pet_Weight = 23.0
                        },
                        new
                        {
                            pet_Id = "fe19b5f0-42b2-4f06-9811-5780356a0bd9",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "BĂC HÀ",
                            pet_ImgUrl1 = "image/giongcho/chobacha.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bulldogmapmapa.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BĂC HÀ",
                            pet_Origin = "BĂC HÀ",
                            pet_OrtherName = "BĂC HÀ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "e3fa8a2d-6e01-44be-8313-f646ed89ae41",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "Pekingese",
                            pet_ImgUrl1 = "image/giongcho/chobackinh.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chowchow.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Pekingese",
                            pet_Origin = "Pekingese",
                            pet_OrtherName = "Pekingese",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "f0c04623-d58a-43a8-a1c1-e3e75f8b8bcb",
                            pet_CategoryId = "a9a31160-91b1-4948-9e37-d7bdc8262531",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cocker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "0ab9a05b-4002-4f74-b031-d0e6fe44098f",
                            pet_CategoryId = "a9a31160-91b1-4948-9e37-d7bdc8262531",
                            pet_Description = "Japan Dog",
                            pet_ImgUrl1 = "image/giongcho/chonhatban.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-pugdangyeu.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Japan Dog",
                            pet_Origin = "Japan Dog",
                            pet_OrtherName = "Japan Dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "d90bc6a8-e83e-418d-81fc-acff88ba4b4f",
                            pet_CategoryId = "5835d336-c69b-4069-baa2-94b8a6708845",
                            pet_Description = "Tibetan Clams",
                            pet_ImgUrl1 = "image/giongcho/ngaottang.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-golden1.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Tibetan Clams",
                            pet_Origin = "Tibetan Clams",
                            pet_OrtherName = "Tibetan Clams",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "35ccf869-803b-47ab-81c8-688623e76b12",
                            pet_CategoryId = "a9a31160-91b1-4948-9e37-d7bdc8262531",
                            pet_Description = "Deer Pug dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-huou.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodlecuoituoi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Deer Pug dog",
                            pet_Origin = "Deer Pug dog",
                            pet_OrtherName = "Deer Pug dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "dc72746a-0e2b-4c47-b4cf-f84706905f80",
                            pet_CategoryId = "5835d336-c69b-4069-baa2-94b8a6708845",
                            pet_Description = "Phoc squirrel dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-soc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chuboss.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phoc squirrel dog",
                            pet_Origin = "Phoc squirrel dog",
                            pet_OrtherName = "Phoc squirrel dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "eddfb58e-47b1-4ee0-9ecc-9f9841f137c4",
                            pet_CategoryId = "5835d336-c69b-4069-baa2-94b8a6708845",
                            pet_Description = "Phu Quoc dogs",
                            pet_ImgUrl1 = "image/giongcho/phu-quoc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgiehalan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phu Quoc dogs",
                            pet_Origin = "Phu Quoc dogs",
                            pet_OrtherName = "Phu Quoc dogs",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "5ef67f26-6c55-4afc-b7e1-43ae25d7298d",
                            pet_CategoryId = "5835d336-c69b-4069-baa2-94b8a6708845",
                            pet_Description = "PITBULL",
                            pet_ImgUrl1 = "image/giongcho/pitbull.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-corgi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "PITBULL",
                            pet_Origin = "PITBULL",
                            pet_OrtherName = "PITBULL",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "618f7f5d-0f2e-4fb5-8cb2-68fc52833f6e",
                            pet_CategoryId = "5ce2eaf4-09b0-49c3-8abb-dc7b4395bb0d",
                            pet_Description = "SHIBA INU ",
                            pet_ImgUrl1 = "image/giongcho/shiba.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuou.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "SHIBA INU ",
                            pet_Origin = "SHIBA INU ",
                            pet_OrtherName = "SHIBA INU ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        });
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.Property<string>("pib_PetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pib_Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pib_PetId", "pib_BillId");

                    b.HasIndex("pib_BillId");

                    b.ToTable("PettInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Property<string>("proc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("proc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("proc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proc_Id");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            proc_Id = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            proc_Description = "newCategories_Id1",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id1"
                        },
                        new
                        {
                            proc_Id = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            proc_Description = "newCategories_Id2",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id2"
                        },
                        new
                        {
                            proc_Id = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            proc_Description = "newCategories_Id3",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id3"
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.Property<string>("proib_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("proib_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("proib_Price")
                        .HasColumnType("float");

                    b.Property<double>("proib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("proib_ProductId", "proib_BillId");

                    b.HasIndex("proib_BillId");

                    b.ToTable("ProductInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("product_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<double>("product_Rate")
                        .HasColumnType("float");

                    b.Property<double>("product_ReProducePrice")
                        .HasColumnType("float");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "4e7a12e6-3a68-4794-818d-de656bf4332c",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Transparent Backpack For Dogs and Cats",
                            product_Img = "image/phukien/phukien-balotrongsuot.png",
                            product_IsDelete = false,
                            product_Name = "Transparent Backpack For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "ac693a77-2885-4d37-83d0-f6dfe77acad4",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Training Whistle",
                            product_Img = "image/phukien/phukien-coihuanluyen.png",
                            product_IsDelete = false,
                            product_Name = "Training Whistle",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "99380e61-a5b6-4f19-9b38-eb6d79899291",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Lamb Sticks",
                            product_Img = "image/phukien/phukien-thitcuuque.png",
                            product_IsDelete = false,
                            product_Name = "Lamb Sticks",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "00e8060d-03bc-4174-b6c0-aaf4602a0192",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "SmartHeart For Small Dogs",
                            product_Img = "image/phukien/phukien-SmartHeart.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Small Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "a67e6253-260d-4242-9bd5-8b1f20c056b3",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Bonus Cake Tablets",
                            product_Img = "image/phukien/phukien-banhthuong.png",
                            product_IsDelete = false,
                            product_Name = "Bonus Cake Tablets",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "c50af542-28c1-4a93-ab3c-3daf06abaa92",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Royal Canin For Adult Dogs",
                            product_Img = "image/phukien/phukien-royal_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Adult Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "df7eb9a3-9282-4b3c-adf0-26e7df1127cf",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Pair of Bows",
                            product_Img = "image/phukien/phukien-capno.png",
                            product_IsDelete = false,
                            product_Name = "Pair of Bows",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "df74d885-67a3-4a0b-a387-447f565a0591",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Princess Lace Scarf",
                            product_Img = "image/phukien/phukien-khanren.png",
                            product_IsDelete = false,
                            product_Name = "Princess Lace Scarf",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "33fb82ab-c90d-49c9-8a7f-59c5d688cad0",
                            product_CategoryId = "cfc64057-a29c-450d-9818-8b78b0ef6219",
                            product_Description = "Drugs of Calcium",
                            product_Img = "image/phukien/phukien-thuoccanxi.png",
                            product_IsDelete = false,
                            product_Name = "Drugs of Calcium",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "aaed4298-4f05-4129-bc02-4ba2465be694",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "Bow Bow Bra",
                            product_Img = "image/phukien/phukien-aongucnochuong.png",
                            product_IsDelete = false,
                            product_Name = "Bow Bow Bra",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "1613759a-fa3d-45b6-8bf3-225537eca838",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "Balloon Toys",
                            product_Img = "image/phukien/phukien-bongbongdochoi.png",
                            product_IsDelete = false,
                            product_Name = "Balloon Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "9310076c-e7a8-4cb7-a640-d009c3f3a11c",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "Dog Fence",
                            product_Img = "image/phukien/phukien-raoquaycho.png",
                            product_IsDelete = false,
                            product_Name = "Dog Fence",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "204be5fc-aa72-4d77-9151-ce80371c2508",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "2bb9be56-0ec1-4ccb-9ab2-7272005254bf",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "Toys",
                            product_Img = "image/phukien/phukien-dochoi.png",
                            product_IsDelete = false,
                            product_Name = "Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "b348fc8e-22ea-41e5-a432-23d7208d3038",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamFay.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "805d5472-5024-4537-8a12-7d125cc97b77",
                            product_CategoryId = "c94afc58-f4a5-44c4-9e07-45f71dc1195a",
                            product_Description = "Anti-Tear Syrup",
                            product_Img = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_IsDelete = false,
                            product_Name = "Anti-Tear Syrup",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "e723da5c-608c-4a4b-a944-77a3249f2b7a",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = "Lice Treatment Ring",
                            product_Img = "image/phukien/phukien-vongtriveran.png",
                            product_IsDelete = false,
                            product_Name = "Lice Treatment Ring",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "fddfe8b4-8f8d-4a7b-a3f0-cbae2eedd9bb",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = "HANTOC Lice Spray",
                            product_Img = "image/phukien/phukien-xitveranHANTOC.png",
                            product_IsDelete = false,
                            product_Name = "HANTOC Lice Spray",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "8c1018a3-1af0-4576-86b0-673e3e4cf15e",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = ">Nutri-Nutrition Gel",
                            product_Img = "image/phukien/phukien-gelddNutri.png",
                            product_IsDelete = false,
                            product_Name = ">Nutri-Nutrition Gel",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "e6df927b-4c60-4e49-b545-072dd88bf087",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = "Bio Milk Powder For Dogs and Cats",
                            product_Img = "image/phukien/phukien-suabotchomeo.png",
                            product_IsDelete = false,
                            product_Name = "Bio Milk Powder For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "4c562982-bf8a-441a-ba46-a1ed936da059",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = "Sleeky Multivitamin",
                            product_Img = "image/phukien/phukien-vitamintonghop.png",
                            product_IsDelete = false,
                            product_Name = "Sleeky Multivitamin",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "968b0983-a47f-436f-ab92-514c77e4a8ee",
                            product_CategoryId = "45ac9daf-11ef-4691-a4e5-bd76435c1c2f",
                            product_Description = "Canxi Nano",
                            product_Img = "image/phukien/phukien-canxinano.png",
                            product_IsDelete = false,
                            product_Name = "Canxi Nano",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.Property<string>("uc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("uc_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uc_Id");

                    b.HasIndex("uc_UserCreate");

                    b.ToTable("UserContact", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "62b9543b-74cd-467f-8d34-069fc12e8fbb",
                            RoleId = "27be5d78-d614-426f-9b7d-7f5f38022483"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "27be5d78-d614-426f-9b7d-7f5f38022483",
                            ConcurrencyStamp = "8897db91-e37f-4547-9226-cc370381599b",
                            Name = "ADMIN",
                            NormalizedName = "admin",
                            Description = "admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");

                    b.HasData(
                        new
                        {
                            Id = "62b9543b-74cd-467f-8d34-069fc12e8fbb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1e01961d-ca13-4752-b4b5-60739d897c3f",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENooTVsOtoGhaApGtiIo8BbzRMJ/4wb67Ckb18OZHYlD6f+SXCCVlZzt10wzuJko4Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aa370f7c-007d-4899-865a-17562aac5cab",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            DoB = new DateTime(2022, 12, 17, 9, 18, 31, 672, DateTimeKind.Local).AddTicks(860),
                            FirstName = "FirstName",
                            LastName = "LastName",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("introducePage")
                        .HasForeignKey("introduce_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.HasOne("Database.Entities.PetCategories", "petCategories")
                        .WithMany("pets")
                        .HasForeignKey("pet_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("petCategories");
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Pets", "pets")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Products", "products")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.HasOne("Database.Entities.ProductCategories", "productCategories")
                        .WithMany("products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("userContact")
                        .HasForeignKey("uc_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Navigation("pettInBill");

                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Navigation("pettInBill");
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.Navigation("introducePage");

                    b.Navigation("userContact");
                });
#pragma warning restore 612, 618
        }
    }
}
