// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221216213918_createdata")]
    partial class createdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("bill_Cancel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StartDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StatusPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_StatusReviceOrder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_Total")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bill_Id");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.Property<string>("introduce_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Zalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("introduce_Id");

                    b.HasIndex("introduce_UserCreate");

                    b.ToTable("IntroducePage", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Property<string>("pc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_Id");

                    b.ToTable("PetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            pc_Id = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pc_Description = "Guard dog",
                            pc_IsDelete = false,
                            pc_Name = "Guard dog"
                        },
                        new
                        {
                            pc_Id = "4ffcfeab-7d9d-4c9a-867a-56aada33d5eb",
                            pc_Description = "Sheepdogs",
                            pc_IsDelete = false,
                            pc_Name = "Sheepdogs"
                        },
                        new
                        {
                            pc_Id = "b309e402-f61f-478f-9cf9-a71b1d09d9be",
                            pc_Description = " Sled dogs",
                            pc_IsDelete = false,
                            pc_Name = " Sled dogs"
                        },
                        new
                        {
                            pc_Id = "14526a08-1aa3-4b71-a9d6-e1305dd60293",
                            pc_Description = "Hound",
                            pc_IsDelete = false,
                            pc_Name = "Hound"
                        });
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Property<string>("pet_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pet_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pet_Lifespan")
                        .HasColumnType("float");

                    b.Property<string>("pet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_OrtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pet_Price")
                        .HasColumnType("float");

                    b.Property<double>("pet_Weight")
                        .HasColumnType("float");

                    b.HasKey("pet_Id");

                    b.HasIndex("pet_CategoryId");

                    b.ToTable("Pets", (string)null);

                    b.HasData(
                        new
                        {
                            pet_Id = "9668c416-811f-46c8-9c68-8e360802f9fd",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cooker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "Japan",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "b84aec74-0d7e-40e8-93e7-c0682090c16e",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BECGIE Belgium (MALINOIS)",
                            pet_ImgUrl1 = "image/giongcho/becgie-bi.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-dobermann-2thang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Belgium (MALINOIS)",
                            pet_Origin = "BECGIE Belgium (MALINOIS)",
                            pet_OrtherName = "BECGIE Belgium (MALINOIS)",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "e21a5c1e-27cc-4ea9-badd-f08fcd2690e2",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BECGIE Germany",
                            pet_ImgUrl1 = "image/giongcho/becgie-duc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodle-rautrang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Germany",
                            pet_Origin = "BECGIE Germany",
                            pet_OrtherName = "BECGIE Germany",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "48a47d36-4399-42a1-85ad-e1b0f73d8317",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BORDER COLLIE",
                            pet_ImgUrl1 = "image/giongcho/BORDER-COLLIE.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuouden.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BORDER COLLIE",
                            pet_Origin = "BORDER COLLIE",
                            pet_OrtherName = "BORDER COLLIE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "88194ebe-2907-49ac-ba55-62afab9521ba",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BULL France",
                            pet_ImgUrl1 = "image/giongcho/bull-phap.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-daingaohusky.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULL France",
                            pet_Origin = "BULL France",
                            pet_OrtherName = "BULL France",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "3d8a9e2b-f45b-4522-a8ed-21346f1f867b",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BULLDOG",
                            pet_ImgUrl1 = "image/giongcho/bulldog.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hoangtutuyetsamoyed.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLDOG",
                            pet_Origin = "BULLDOG",
                            pet_OrtherName = "BULLDOG",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "ff2cbae5-6b2f-4386-bafc-769ae9562997",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BULLY AMERICAN",
                            pet_ImgUrl1 = "image/giongcho/bully-american.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliecongchua.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLY AMERICAN",
                            pet_Origin = "BULLY AMERICAN",
                            pet_OrtherName = "BULLY AMERICAN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "41da7669-a1e1-44c7-9646-af396f2d1f45",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "CHIHUAHUA",
                            pet_ImgUrl1 = "image/giongcho/chihuahua.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phosocnhonhan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHIHUAHUA",
                            pet_Origin = "CHIHUAHUA",
                            pet_OrtherName = "CHIHUAHUA",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "fc4e05ab-32f0-417b-9a03-ef4dc584b783",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cogaipitbull.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "7194233f-9938-4122-95b9-21331f5b5e77",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "CHOW CHOW",
                            pet_ImgUrl1 = "image/giongcho/chow-chow.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliemui2.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHOW CHOW",
                            pet_Origin = "CHOW CHOW",
                            pet_OrtherName = "CHOW CHOW",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "e39a3cf7-977c-4744-ac38-1471cf56aa93",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "CORGI",
                            pet_ImgUrl1 = "image/giongcho/corgy.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goodboyrottweiler.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CORGI",
                            pet_Origin = "CORGI",
                            pet_OrtherName = "CORGI",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "8cab3f8b-0f8b-4293-9144-474ada0166d9",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "DOBERMANN",
                            pet_ImgUrl1 = "image/giongcho/dobermann.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hotboylabrador.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "DOBERMANN",
                            pet_Origin = "DOBERMANN",
                            pet_OrtherName = "DOBERMANN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "8f033b4a-0e71-4e8a-b0b7-702efd808922",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "GOLDEN RETRIEVER",
                            pet_ImgUrl1 = "image/giongcho/golden-retriever.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgieduc.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GOLDEN RETRIEVER",
                            pet_Origin = "GOLDEN RETRIEVER",
                            pet_OrtherName = "GOLDEN RETRIEVER",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "850e2f65-bb8f-424c-96f0-a9f268842e51",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "GREAT DANE",
                            pet_ImgUrl1 = "image/giongcho/great-dane.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-lapxuongsocola.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GREAT DANE",
                            pet_Origin = "GREAT DANE",
                            pet_OrtherName = "GREAT DANE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "f2049ece-6782-4d7a-9731-54462c5e2a79",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "H'Mong Coc",
                            pet_ImgUrl1 = "image/giongcho/mong-coc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuoutimsen.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "H'Mong Coc",
                            pet_Origin = "H'Mong Coc",
                            pet_OrtherName = "H'Mong Coc",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "b69125ed-826b-4cff-b092-581d280b554e",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goldenretriever.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "AKITA INU",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "4296c53c-7461-4bf1-b030-7df7bc782b12",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "ALASKA",
                            pet_ImgUrl1 = "image/giongcho/alaska.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-alaskamummim.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "ALASKA",
                            pet_Origin = "ALASKA",
                            pet_OrtherName = "ALASKA",
                            pet_Price = 100.0,
                            pet_Weight = 23.0
                        },
                        new
                        {
                            pet_Id = "c2fd3022-670d-406b-a8fa-9537d66819df",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "BĂC HÀ",
                            pet_ImgUrl1 = "image/giongcho/chobacha.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bulldogmapmapa.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BĂC HÀ",
                            pet_Origin = "BĂC HÀ",
                            pet_OrtherName = "BĂC HÀ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "85439d8a-7fa2-47a0-ac68-be93e4de466f",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "Pekingese",
                            pet_ImgUrl1 = "image/giongcho/chobackinh.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chowchow.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Pekingese",
                            pet_Origin = "Pekingese",
                            pet_OrtherName = "Pekingese",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "6011c080-4b43-487f-becc-ea0c94d36b22",
                            pet_CategoryId = "4ffcfeab-7d9d-4c9a-867a-56aada33d5eb",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cocker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "12e44638-8cb3-466c-8b63-6ff0ac1803f8",
                            pet_CategoryId = "4ffcfeab-7d9d-4c9a-867a-56aada33d5eb",
                            pet_Description = "Japan Dog",
                            pet_ImgUrl1 = "image/giongcho/chonhatban.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-pugdangyeu.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Japan Dog",
                            pet_Origin = "Japan Dog",
                            pet_OrtherName = "Japan Dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "27c87c2e-3520-4444-adbe-94d29f9b7191",
                            pet_CategoryId = "b309e402-f61f-478f-9cf9-a71b1d09d9be",
                            pet_Description = "Tibetan Clams",
                            pet_ImgUrl1 = "image/giongcho/ngaottang.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-golden1.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Tibetan Clams",
                            pet_Origin = "Tibetan Clams",
                            pet_OrtherName = "Tibetan Clams",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "bdf0f686-c7f7-400b-adb9-521128dbb30d",
                            pet_CategoryId = "4ffcfeab-7d9d-4c9a-867a-56aada33d5eb",
                            pet_Description = "Deer Pug dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-huou.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodlecuoituoi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Deer Pug dog",
                            pet_Origin = "Deer Pug dog",
                            pet_OrtherName = "Deer Pug dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "177eadba-125d-4d18-9ab0-51f0a0eff0b4",
                            pet_CategoryId = "b309e402-f61f-478f-9cf9-a71b1d09d9be",
                            pet_Description = "Phoc squirrel dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-soc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chuboss.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phoc squirrel dog",
                            pet_Origin = "Phoc squirrel dog",
                            pet_OrtherName = "Phoc squirrel dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "a4736e34-8ecc-496d-b3ce-e70ff47487ef",
                            pet_CategoryId = "b309e402-f61f-478f-9cf9-a71b1d09d9be",
                            pet_Description = "Phu Quoc dogs",
                            pet_ImgUrl1 = "image/giongcho/phu-quoc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgiehalan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phu Quoc dogs",
                            pet_Origin = "Phu Quoc dogs",
                            pet_OrtherName = "Phu Quoc dogs",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "a5c3cd24-54d0-4187-af73-ae743d263048",
                            pet_CategoryId = "b309e402-f61f-478f-9cf9-a71b1d09d9be",
                            pet_Description = "PITBULL",
                            pet_ImgUrl1 = "image/giongcho/pitbull.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-corgi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "PITBULL",
                            pet_Origin = "PITBULL",
                            pet_OrtherName = "PITBULL",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "38193e75-1cba-4bd6-8ee9-ca74ca0f41aa",
                            pet_CategoryId = "ec4ac5f5-f450-4688-97ed-11a2dee12255",
                            pet_Description = "SHIBA INU ",
                            pet_ImgUrl1 = "image/giongcho/shiba.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuou.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "SHIBA INU ",
                            pet_Origin = "SHIBA INU ",
                            pet_OrtherName = "SHIBA INU ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        });
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.Property<string>("pib_PetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pib_Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pib_PetId", "pib_BillId");

                    b.HasIndex("pib_BillId");

                    b.ToTable("PettInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Property<string>("proc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("proc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("proc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proc_Id");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            proc_Id = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            proc_Description = "newCategories_Id1",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id1"
                        },
                        new
                        {
                            proc_Id = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            proc_Description = "newCategories_Id2",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id2"
                        },
                        new
                        {
                            proc_Id = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            proc_Description = "newCategories_Id3",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id3"
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.Property<string>("proib_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("proib_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("proib_Price")
                        .HasColumnType("float");

                    b.Property<double>("proib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("proib_ProductId", "proib_BillId");

                    b.HasIndex("proib_BillId");

                    b.ToTable("ProductInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("product_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<double>("product_Rate")
                        .HasColumnType("float");

                    b.Property<double>("product_ReProducePrice")
                        .HasColumnType("float");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "348c52de-016c-4d8e-80be-f5ee90c6bb62",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Transparent Backpack For Dogs and Cats",
                            product_Img = "image/phukien/phukien-balotrongsuot.png",
                            product_IsDelete = false,
                            product_Name = "Transparent Backpack For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "43ac8d92-5467-4afd-9d2b-e55541323b16",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Training Whistle",
                            product_Img = "image/phukien/phukien-coihuanluyen.png",
                            product_IsDelete = false,
                            product_Name = "Training Whistle",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "d1e56bd2-c1b3-4915-bb16-36dc434e5253",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Lamb Sticks",
                            product_Img = "image/phukien/phukien-thitcuuque.png",
                            product_IsDelete = false,
                            product_Name = "Lamb Sticks",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "c42d6397-c4a2-4a01-8bc1-55ad38202071",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "SmartHeart For Small Dogs",
                            product_Img = "image/phukien/phukien-SmartHeart.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Small Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "6b2f7205-fdc3-40d7-8de8-0015c88383bf",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Bonus Cake Tablets",
                            product_Img = "image/phukien/phukien-banhthuong.png",
                            product_IsDelete = false,
                            product_Name = "Bonus Cake Tablets",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "3f72c5cb-ecb6-4af1-a6de-639753d225f9",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Royal Canin For Adult Dogs",
                            product_Img = "image/phukien/phukien-royal_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Adult Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "be8ae287-0442-49e7-8023-3757d76e6483",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Pair of Bows",
                            product_Img = "image/phukien/phukien-capno.png",
                            product_IsDelete = false,
                            product_Name = "Pair of Bows",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "63e0c2cf-929e-4bac-9bc6-826cf1180ec5",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Princess Lace Scarf",
                            product_Img = "image/phukien/phukien-khanren.png",
                            product_IsDelete = false,
                            product_Name = "Princess Lace Scarf",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "16a5be4b-43b6-40ce-a969-83d5e4637224",
                            product_CategoryId = "745d7d09-1a46-4c4b-9ced-443519e50b2d",
                            product_Description = "Drugs of Calcium",
                            product_Img = "image/phukien/phukien-thuoccanxi.png",
                            product_IsDelete = false,
                            product_Name = "Drugs of Calcium",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "4f2f01ff-ea94-47a4-927a-3981dff55b65",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "Bow Bow Bra",
                            product_Img = "image/phukien/phukien-aongucnochuong.png",
                            product_IsDelete = false,
                            product_Name = "Bow Bow Bra",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "20397d1b-3790-43c0-bfc6-63be7f6cc27b",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "Balloon Toys",
                            product_Img = "image/phukien/phukien-bongbongdochoi.png",
                            product_IsDelete = false,
                            product_Name = "Balloon Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "b2bfefcc-e629-4ece-82b8-1693230c80ae",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "Dog Fence",
                            product_Img = "image/phukien/phukien-raoquaycho.png",
                            product_IsDelete = false,
                            product_Name = "Dog Fence",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "80eef068-c421-40ff-b720-79e8232f82a9",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "afee0090-ac14-49cc-b9e3-4a2378aa7648",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "Toys",
                            product_Img = "image/phukien/phukien-dochoi.png",
                            product_IsDelete = false,
                            product_Name = "Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "4d2f80e7-9b27-4aeb-af43-fc1110217691",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamFay.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "138706ba-9eb8-4835-b855-4488b56344b6",
                            product_CategoryId = "be12ceb7-6d18-41dc-a0f4-746ea177237c",
                            product_Description = "Anti-Tear Syrup",
                            product_Img = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_IsDelete = false,
                            product_Name = "Anti-Tear Syrup",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "feb14734-5dd5-40f5-a94a-45e28b32b176",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = "Lice Treatment Ring",
                            product_Img = "image/phukien/phukien-vongtriveran.png",
                            product_IsDelete = false,
                            product_Name = "Lice Treatment Ring",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "e8e7bc6f-506e-46b0-a83a-b37a7631d1f2",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = "HANTOC Lice Spray",
                            product_Img = "image/phukien/phukien-xitveranHANTOC.png",
                            product_IsDelete = false,
                            product_Name = "HANTOC Lice Spray",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "8629218b-65ca-436f-a105-31d7350d1e67",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = ">Nutri-Nutrition Gel",
                            product_Img = "image/phukien/phukien-gelddNutri.png",
                            product_IsDelete = false,
                            product_Name = ">Nutri-Nutrition Gel",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "226b8393-9fdb-4e76-aa94-3fb1dad96d3d",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = "Bio Milk Powder For Dogs and Cats",
                            product_Img = "image/phukien/phukien-suabotchomeo.png",
                            product_IsDelete = false,
                            product_Name = "Bio Milk Powder For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "2c8d51e1-9978-474f-a16e-e62af747c3c0",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = "Sleeky Multivitamin",
                            product_Img = "image/phukien/phukien-vitamintonghop.png",
                            product_IsDelete = false,
                            product_Name = "Sleeky Multivitamin",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "6ef0f541-26e7-4ef4-8194-77d43ae79eca",
                            product_CategoryId = "9a980683-2470-4457-8ccc-14b3e5c0f29d",
                            product_Description = "Canxi Nano",
                            product_Img = "image/phukien/phukien-canxinano.png",
                            product_IsDelete = false,
                            product_Name = "Canxi Nano",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.Property<string>("uc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("uc_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uc_Id");

                    b.HasIndex("uc_UserCreate");

                    b.ToTable("UserContact", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1ae4d372-d977-44e0-878e-3ccbff40cac9",
                            RoleId = "d1cede10-3320-4ab4-980c-6b6dec513ec6"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "d1cede10-3320-4ab4-980c-6b6dec513ec6",
                            ConcurrencyStamp = "5840055d-fdaf-4476-b0a1-cc6b23f77efb",
                            Name = "ADMIN",
                            NormalizedName = "admin",
                            Description = "admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");

                    b.HasData(
                        new
                        {
                            Id = "1ae4d372-d977-44e0-878e-3ccbff40cac9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2b50de82-954e-42fd-912f-77a9a129f012",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMeq6sm9Y+RqmDrSfPoF+0jSgWsyuYM21TdIk+uwbGIPm6tCFgWx/x2dv2UdMSp1wA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a877bff-45b0-4b41-90e0-113c1cf8ccb4",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            DoB = new DateTime(2022, 12, 17, 4, 39, 18, 592, DateTimeKind.Local).AddTicks(6565),
                            FirstName = "FirstName",
                            LastName = "LastName",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("introducePage")
                        .HasForeignKey("introduce_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.HasOne("Database.Entities.PetCategories", "petCategories")
                        .WithMany("pets")
                        .HasForeignKey("pet_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("petCategories");
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Pets", "pets")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Products", "products")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.HasOne("Database.Entities.ProductCategories", "productCategories")
                        .WithMany("products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("userContact")
                        .HasForeignKey("uc_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Navigation("pettInBill");

                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Navigation("pettInBill");
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.Navigation("introducePage");

                    b.Navigation("userContact");
                });
#pragma warning restore 612, 618
        }
    }
}
