// <auto-generated />
using System;
using Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_Cancel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("bill_StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_StatusPayment")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_StatusReviceOrder")
                        .HasColumnType("bit");

                    b.Property<double>("bill_Total")
                        .HasColumnType("float");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("bill_checkout")
                        .HasColumnType("bit");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.Property<string>("introduce_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Map3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("introduce_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("introduce_Zalo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("introduce_Id");

                    b.HasIndex("introduce_UserCreate");

                    b.ToTable("IntroducePage", (string)null);
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Property<string>("pc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("pc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pc_Id");

                    b.ToTable("PetCategories", (string)null);

                    b.HasData(
                        new
                        {
                            pc_Id = "645409a1-731c-448b-ada0-e5fafc822338",
                            pc_Description = "Guard dog",
                            pc_IsDelete = false,
                            pc_Name = "Guard dog"
                        },
                        new
                        {
                            pc_Id = "03b6655d-31c8-4ce7-8e4f-98bf9c68f9ce",
                            pc_Description = "Sheepdogs",
                            pc_IsDelete = false,
                            pc_Name = "Sheepdogs"
                        },
                        new
                        {
                            pc_Id = "c25a39e8-a630-402e-9203-9c08254f0170",
                            pc_Description = " Sled dogs",
                            pc_IsDelete = false,
                            pc_Name = " Sled dogs"
                        },
                        new
                        {
                            pc_Id = "4a88cce7-6f7a-4c1a-a52d-f6c6ac9f7541",
                            pc_Description = "Hound",
                            pc_IsDelete = false,
                            pc_Name = "Hound"
                        });
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Property<string>("pet_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pet_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_ImgUrl4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("pet_IsDelete")
                        .HasColumnType("bit");

                    b.Property<double>("pet_Lifespan")
                        .HasColumnType("float");

                    b.Property<string>("pet_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pet_OrtherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("pet_Price")
                        .HasColumnType("float");

                    b.Property<double>("pet_Weight")
                        .HasColumnType("float");

                    b.HasKey("pet_Id");

                    b.HasIndex("pet_CategoryId");

                    b.ToTable("Pets", (string)null);

                    b.HasData(
                        new
                        {
                            pet_Id = "50c7d1af-60bb-427a-bb76-a4e47d85f50a",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cooker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "Japan",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "3672613e-b2bb-4d15-a747-0481e39a75b4",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BECGIE Belgium (MALINOIS)",
                            pet_ImgUrl1 = "image/giongcho/becgie-bi.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-dobermann-2thang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Belgium (MALINOIS)",
                            pet_Origin = "BECGIE Belgium (MALINOIS)",
                            pet_OrtherName = "BECGIE Belgium (MALINOIS)",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "5cdd717b-1d01-4cee-b33b-dc982a5b4394",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BECGIE Germany",
                            pet_ImgUrl1 = "image/giongcho/becgie-duc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodle-rautrang.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 10.0,
                            pet_Name = "BECGIE Germany",
                            pet_Origin = "BECGIE Germany",
                            pet_OrtherName = "BECGIE Germany",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "7c81c711-2b55-46bb-839c-8cbb81483561",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BORDER COLLIE",
                            pet_ImgUrl1 = "image/giongcho/BORDER-COLLIE.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuouden.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BORDER COLLIE",
                            pet_Origin = "BORDER COLLIE",
                            pet_OrtherName = "BORDER COLLIE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "b3aad5bb-fc85-49d5-b2a9-66dd01f5fdf3",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BULL France",
                            pet_ImgUrl1 = "image/giongcho/bull-phap.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-daingaohusky.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULL France",
                            pet_Origin = "BULL France",
                            pet_OrtherName = "BULL France",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "e6578af4-59bf-4422-a0a3-59612d82e6fc",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BULLDOG",
                            pet_ImgUrl1 = "image/giongcho/bulldog.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hoangtutuyetsamoyed.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLDOG",
                            pet_Origin = "BULLDOG",
                            pet_OrtherName = "BULLDOG",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "b3e7ee3a-d367-4f5b-a3cf-bac4c610cbf4",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BULLY AMERICAN",
                            pet_ImgUrl1 = "image/giongcho/bully-american.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliecongchua.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BULLY AMERICAN",
                            pet_Origin = "BULLY AMERICAN",
                            pet_OrtherName = "BULLY AMERICAN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "de1f4f56-3612-4f1a-ba3f-3b20c40b1ded",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "CHIHUAHUA",
                            pet_ImgUrl1 = "image/giongcho/chihuahua.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phosocnhonhan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHIHUAHUA",
                            pet_Origin = "CHIHUAHUA",
                            pet_OrtherName = "CHIHUAHUA",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "a02eedc9-03bf-40b2-8300-ea664bda1ca4",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cogaipitbull.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "44b4986f-b7a6-4594-bd41-ebf85fc5c973",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "CHOW CHOW",
                            pet_ImgUrl1 = "image/giongcho/chow-chow.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bordercolliemui2.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CHOW CHOW",
                            pet_Origin = "CHOW CHOW",
                            pet_OrtherName = "CHOW CHOW",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "a37f916a-d234-4d16-b122-1224766eac4a",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "CORGI",
                            pet_ImgUrl1 = "image/giongcho/corgy.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goodboyrottweiler.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "CORGI",
                            pet_Origin = "CORGI",
                            pet_OrtherName = "CORGI",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "a8ccf0ea-647c-4663-a0e4-a571265cf0a8",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "DOBERMANN",
                            pet_ImgUrl1 = "image/giongcho/dobermann.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-hotboylabrador.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "DOBERMANN",
                            pet_Origin = "DOBERMANN",
                            pet_OrtherName = "DOBERMANN",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "0fb10822-26d5-4e49-8de6-23b13ba8c7f4",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "GOLDEN RETRIEVER",
                            pet_ImgUrl1 = "image/giongcho/golden-retriever.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgieduc.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GOLDEN RETRIEVER",
                            pet_Origin = "GOLDEN RETRIEVER",
                            pet_OrtherName = "GOLDEN RETRIEVER",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "1cfe5ebe-1895-4c02-954c-9a505fe508d7",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "GREAT DANE",
                            pet_ImgUrl1 = "image/giongcho/great-dane.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-lapxuongsocola.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "GREAT DANE",
                            pet_Origin = "GREAT DANE",
                            pet_OrtherName = "GREAT DANE",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "69818ec6-b92a-4d4c-aa75-c7a31cea41b6",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "H'Mong Coc",
                            pet_ImgUrl1 = "image/giongcho/mong-coc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuoutimsen.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "H'Mong Coc",
                            pet_Origin = "H'Mong Coc",
                            pet_OrtherName = "H'Mong Coc",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "381c18df-d43d-48af-b717-0f88eb10d511",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "AKITA INU",
                            pet_ImgUrl1 = "image/giongcho/akita-inu.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-goldenretriever.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "AKITA INU",
                            pet_Origin = "AKITA INU",
                            pet_OrtherName = "AKITA INU",
                            pet_Price = 100.0,
                            pet_Weight = 32.0
                        },
                        new
                        {
                            pet_Id = "e3da9e22-34cc-41d3-be97-0f72271aef3e",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "ALASKA",
                            pet_ImgUrl1 = "image/giongcho/alaska.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-alaskamummim.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "ALASKA",
                            pet_Origin = "ALASKA",
                            pet_OrtherName = "ALASKA",
                            pet_Price = 100.0,
                            pet_Weight = 23.0
                        },
                        new
                        {
                            pet_Id = "ddb00b82-f8ce-482b-be88-445797640bbb",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "BĂC HÀ",
                            pet_ImgUrl1 = "image/giongcho/chobacha.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-bulldogmapmapa.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "BĂC HÀ",
                            pet_Origin = "BĂC HÀ",
                            pet_OrtherName = "BĂC HÀ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "5f9ca535-1625-4041-91a7-9a7f33174d74",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "Pekingese",
                            pet_ImgUrl1 = "image/giongcho/chobackinh.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chowchow.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Pekingese",
                            pet_Origin = "Pekingese",
                            pet_OrtherName = "Pekingese",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "ee25e3bc-b06b-428c-9be4-1af28f579d7e",
                            pet_CategoryId = "03b6655d-31c8-4ce7-8e4f-98bf9c68f9ce",
                            pet_Description = "Dalmatian",
                            pet_ImgUrl1 = "image/giongcho/cho-dom.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-cocker.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Dalmatian",
                            pet_Origin = "Dalmatian",
                            pet_OrtherName = "Dalmatian",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "b56403e2-5341-4fbe-a9b8-e8dd609c6544",
                            pet_CategoryId = "03b6655d-31c8-4ce7-8e4f-98bf9c68f9ce",
                            pet_Description = "Japan Dog",
                            pet_ImgUrl1 = "image/giongcho/chonhatban.png",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-pugdangyeu.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Japan Dog",
                            pet_Origin = "Japan Dog",
                            pet_OrtherName = "Japan Dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "f20146c8-4023-405b-88f0-bd376a76ea89",
                            pet_CategoryId = "c25a39e8-a630-402e-9203-9c08254f0170",
                            pet_Description = "Tibetan Clams",
                            pet_ImgUrl1 = "image/giongcho/ngaottang.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-golden1.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Tibetan Clams",
                            pet_Origin = "Tibetan Clams",
                            pet_OrtherName = "Tibetan Clams",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "6b50cdc8-ba9c-4125-802b-5ee9d2224146",
                            pet_CategoryId = "03b6655d-31c8-4ce7-8e4f-98bf9c68f9ce",
                            pet_Description = "Deer Pug dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-huou.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-poodlecuoituoi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Deer Pug dog",
                            pet_Origin = "Deer Pug dog",
                            pet_OrtherName = "Deer Pug dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "76b67383-6ccd-4cea-ab1f-33157aa811e2",
                            pet_CategoryId = "c25a39e8-a630-402e-9203-9c08254f0170",
                            pet_Description = "Phoc squirrel dog",
                            pet_ImgUrl1 = "image/giongcho/phoc-soc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-chuboss.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phoc squirrel dog",
                            pet_Origin = "Phoc squirrel dog",
                            pet_OrtherName = "Phoc squirrel dog",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "409a519f-2989-4df3-91fe-f10c3778ad56",
                            pet_CategoryId = "c25a39e8-a630-402e-9203-9c08254f0170",
                            pet_Description = "Phu Quoc dogs",
                            pet_ImgUrl1 = "image/giongcho/phu-quoc.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-becgiehalan.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "Phu Quoc dogs",
                            pet_Origin = "Phu Quoc dogs",
                            pet_OrtherName = "Phu Quoc dogs",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "025cf78e-8362-430a-a5c3-148bb816c249",
                            pet_CategoryId = "c25a39e8-a630-402e-9203-9c08254f0170",
                            pet_Description = "PITBULL",
                            pet_ImgUrl1 = "image/giongcho/pitbull.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-corgi.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "PITBULL",
                            pet_Origin = "PITBULL",
                            pet_OrtherName = "PITBULL",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        },
                        new
                        {
                            pet_Id = "e93ee443-c046-4afc-a620-66c51ebd5e8e",
                            pet_CategoryId = "645409a1-731c-448b-ada0-e5fafc822338",
                            pet_Description = "SHIBA INU ",
                            pet_ImgUrl1 = "image/giongcho/shiba.jpg",
                            pet_ImgUrl2 = "",
                            pet_ImgUrl3 = "",
                            pet_ImgUrl4 = "image/cuncon/cuncon-phochuou.jpg",
                            pet_IsDelete = false,
                            pet_Lifespan = 12.0,
                            pet_Name = "SHIBA INU ",
                            pet_Origin = "SHIBA INU ",
                            pet_OrtherName = "SHIBA INU ",
                            pet_Price = 100.0,
                            pet_Weight = 33.0
                        });
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.Property<string>("pib_PetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("pib_Quantity")
                        .HasColumnType("int");

                    b.HasKey("pib_PetId", "pib_BillId");

                    b.HasIndex("pib_BillId");

                    b.ToTable("PettInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Property<string>("proc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proc_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("proc_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("proc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("proc_Id");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            proc_Id = "1e40491c-bce9-4be3-b282-7bf185382097",
                            proc_Description = "newCategories_Id1",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id1"
                        },
                        new
                        {
                            proc_Id = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            proc_Description = "newCategories_Id2",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id2"
                        },
                        new
                        {
                            proc_Id = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            proc_Description = "newCategories_Id3",
                            proc_IsDelete = false,
                            proc_Name = "newCategories_Id3"
                        });
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.Property<string>("proib_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("proib_BillId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("proib_Quantity")
                        .HasColumnType("float");

                    b.HasKey("proib_ProductId", "proib_BillId");

                    b.HasIndex("proib_BillId");

                    b.ToTable("ProductInBill", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("product_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<double>("product_Rate")
                        .HasColumnType("float");

                    b.Property<double>("product_ReProducePrice")
                        .HasColumnType("float");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "296a6e09-6db1-4ad5-bfd5-ff03bb846598",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Transparent Backpack For Dogs and Cats",
                            product_Img = "image/phukien/phukien-balotrongsuot.png",
                            product_IsDelete = false,
                            product_Name = "Transparent Backpack For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "c0db9a58-45a2-4a82-92eb-8b34f136faf3",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Training Whistle",
                            product_Img = "image/phukien/phukien-coihuanluyen.png",
                            product_IsDelete = false,
                            product_Name = "Training Whistle",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "97160a1f-dded-4ca1-9136-e3a5012d2fd8",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Lamb Sticks",
                            product_Img = "image/phukien/phukien-thitcuuque.png",
                            product_IsDelete = false,
                            product_Name = "Lamb Sticks",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "35aaacf5-54e3-4c1b-a6d1-6cf8ad7f3ed7",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "SmartHeart For Small Dogs",
                            product_Img = "image/phukien/phukien-SmartHeart.png",
                            product_IsDelete = false,
                            product_Name = "SmartHeart For Small Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "c9af8312-6e80-4649-a593-115a41322f69",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Bonus Cake Tablets",
                            product_Img = "image/phukien/phukien-banhthuong.png",
                            product_IsDelete = false,
                            product_Name = "Bonus Cake Tablets",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "3630e7fc-8643-4959-9916-c9b435d3e757",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Royal Canin For Adult Dogs",
                            product_Img = "image/phukien/phukien-royal_truongthanh.png",
                            product_IsDelete = false,
                            product_Name = "Royal Canin For Adult Dogs",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "cc95d4e5-13b7-4731-a412-c8c23874090e",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Pair of Bows",
                            product_Img = "image/phukien/phukien-capno.png",
                            product_IsDelete = false,
                            product_Name = "Pair of Bows",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "03992d7c-2fe8-49b8-ba6f-c5187bfabb85",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Princess Lace Scarf",
                            product_Img = "image/phukien/phukien-khanren.png",
                            product_IsDelete = false,
                            product_Name = "Princess Lace Scarf",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "506f1da3-f5c3-4b78-bbf0-ce6581c97dbc",
                            product_CategoryId = "1e40491c-bce9-4be3-b282-7bf185382097",
                            product_Description = "Drugs of Calcium",
                            product_Img = "image/phukien/phukien-thuoccanxi.png",
                            product_IsDelete = false,
                            product_Name = "Drugs of Calcium",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "317cc30d-8ff6-48c9-90f7-5b8aa549c440",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "Bow Bow Bra",
                            product_Img = "image/phukien/phukien-aongucnochuong.png",
                            product_IsDelete = false,
                            product_Name = "Bow Bow Bra",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "a82ad01c-8b38-42bd-8b63-2f7631ae2f6c",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "Balloon Toys",
                            product_Img = "image/phukien/phukien-bongbongdochoi.png",
                            product_IsDelete = false,
                            product_Name = "Balloon Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "a43da1a9-80ae-4d72-b20f-7e715c231dbd",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "Dog Fence",
                            product_Img = "image/phukien/phukien-raoquaycho.png",
                            product_IsDelete = false,
                            product_Name = "Dog Fence",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "3463dda1-1cf9-49ad-9f8c-d75c5dc1b6ec",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamnuochoabloomsexy.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "7a84859d-9731-4bd5-9959-2631c064087d",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "Toys",
                            product_Img = "image/phukien/phukien-dochoi.png",
                            product_IsDelete = false,
                            product_Name = "Toys",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "eb0aec04-c1a7-4adb-b0ee-392eaa8d4afb",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "BLOOM SEXY Fragrance Bath Oil",
                            product_Img = "image/phukien/phukien-dautamFay.png",
                            product_IsDelete = false,
                            product_Name = "BLOOM SEXY Fragrance Bath Oil",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "7f916f6f-dfc3-4b7a-bce1-848fb4aae595",
                            product_CategoryId = "cd684801-3d02-4009-bb1d-bc65dc6738a3",
                            product_Description = "Anti-Tear Syrup",
                            product_Img = "image/phukien/phukien-sirochongchaynuocmat.png",
                            product_IsDelete = false,
                            product_Name = "Anti-Tear Syrup",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "82f5ef25-4612-42eb-aeb9-b8189fca14f9",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = "Lice Treatment Ring",
                            product_Img = "image/phukien/phukien-vongtriveran.png",
                            product_IsDelete = false,
                            product_Name = "Lice Treatment Ring",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "46c3a718-dc26-4af6-b200-b5f6f17ff121",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = "HANTOC Lice Spray",
                            product_Img = "image/phukien/phukien-xitveranHANTOC.png",
                            product_IsDelete = false,
                            product_Name = "HANTOC Lice Spray",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "0c1acc88-8d1a-49fb-98df-2a14e980d6cd",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = ">Nutri-Nutrition Gel",
                            product_Img = "image/phukien/phukien-gelddNutri.png",
                            product_IsDelete = false,
                            product_Name = ">Nutri-Nutrition Gel",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "7e9a4757-d12f-4a07-a1e1-e7c8658dbf30",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = "Bio Milk Powder For Dogs and Cats",
                            product_Img = "image/phukien/phukien-suabotchomeo.png",
                            product_IsDelete = false,
                            product_Name = "Bio Milk Powder For Dogs and Cats",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "6395a643-387e-4254-a4f3-068f20dbe871",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = "Sleeky Multivitamin",
                            product_Img = "image/phukien/phukien-vitamintonghop.png",
                            product_IsDelete = false,
                            product_Name = "Sleeky Multivitamin",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        },
                        new
                        {
                            product_Id = "934005a2-8792-4229-978a-bea9de59cd71",
                            product_CategoryId = "32d0fda1-2ba5-4018-b264-09ca7fa01d70",
                            product_Description = "Canxi Nano",
                            product_Img = "image/phukien/phukien-canxinano.png",
                            product_IsDelete = false,
                            product_Name = "Canxi Nano",
                            product_Price = 10.0,
                            product_Rate = 1.0,
                            product_ReProducePrice = 1.0
                        });
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.Property<string>("uc_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("uc_Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_IsDelete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("uc_UserCreate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("uc_Id");

                    b.HasIndex("uc_UserCreate");

                    b.ToTable("UserContact", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "10774c91-abc4-499a-a005-782459584950",
                            RoleId = "b87a3e7d-4b73-4322-847a-dbc2d76f8307"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Database.Entities.Roles", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Roles");

                    b.HasDiscriminator().HasValue("Roles");

                    b.HasData(
                        new
                        {
                            Id = "b87a3e7d-4b73-4322-847a-dbc2d76f8307",
                            ConcurrencyStamp = "1279767f-a908-4dd9-bb42-0bf31fc8cd13",
                            Name = "ADMIN",
                            NormalizedName = "admin",
                            Description = "admin",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Users");

                    b.HasData(
                        new
                        {
                            Id = "10774c91-abc4-499a-a005-782459584950",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cfcebd27-53e2-4f95-a4e7-9e7a28a90194",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECrFJlUSl4n1/b7KLAdx5DLPnHtKgnYnDOAzl5zrnv6DYHQFyVlR06KgGYwUvWJYCQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "258e6ce2-5876-4ce0-8e16-b7b3d3eab645",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            DoB = new DateTime(2022, 12, 17, 11, 27, 20, 200, DateTimeKind.Local).AddTicks(7657),
                            FirstName = "FirstName",
                            LastName = "LastName",
                            isDelete = false
                        });
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.HasOne("Database.Entities.Users", "Users")
                        .WithMany("bill")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Database.Entities.IntroducePage", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("introducePage")
                        .HasForeignKey("introduce_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.HasOne("Database.Entities.PetCategories", "petCategories")
                        .WithMany("pets")
                        .HasForeignKey("pet_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("petCategories");
                });

            modelBuilder.Entity("Database.Entities.PettInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Pets", "pets")
                        .WithMany("pettInBill")
                        .HasForeignKey("pib_PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.ProductInBill", b =>
                {
                    b.HasOne("Database.Entities.Bills", "bills")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Entities.Products", "products")
                        .WithMany("productInBill")
                        .HasForeignKey("proib_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bills");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.HasOne("Database.Entities.ProductCategories", "productCategories")
                        .WithMany("products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategories");
                });

            modelBuilder.Entity("Database.Entities.UserContact", b =>
                {
                    b.HasOne("Database.Entities.Users", "users")
                        .WithMany("userContact")
                        .HasForeignKey("uc_UserCreate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database.Entities.Bills", b =>
                {
                    b.Navigation("pettInBill");

                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.PetCategories", b =>
                {
                    b.Navigation("pets");
                });

            modelBuilder.Entity("Database.Entities.Pets", b =>
                {
                    b.Navigation("pettInBill");
                });

            modelBuilder.Entity("Database.Entities.ProductCategories", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Database.Entities.Products", b =>
                {
                    b.Navigation("productInBill");
                });

            modelBuilder.Entity("Database.Entities.Users", b =>
                {
                    b.Navigation("bill");

                    b.Navigation("introducePage");

                    b.Navigation("userContact");
                });
#pragma warning restore 612, 618
        }
    }
}
